### ISSUE TITLE
Use the orthographic camera in all 2D image presentations

### ISSUE THREAD

**Issue by andy-sweet** [chanzuckerberg/idetik#78]
Many of the 2D image presentation examples still use the perspective camera. Instead they should use the orthographic camera. As part of this, we may also wish to fix some of the hard coded coordinates associated with the image plane geometry (related to https://github.com/chanzuckerberg/imaging-active-learning/issues/35).

**Comment by andy-sweet** [comment]
Another possible goal of this issue (that I'd really like to see!) is to ensure that the aspect ratio of the rendered image data is respected. I'm not sure if this should be handled by geometry coordinates or transforms (though I lean towards coordinates). Currently, our main example presents a 1920x1440 image in a 3x3 plane.

**Comment by aganders3** [comment]
> aspect ratio of the rendered image data is respected. I'm not sure if this should be handled by geometry coordinates or transforms (though I lean towards coordinates).

This is a great point. Initially I would lean towards adjusting coordinates for this as well, but I could see it going both ways. Using the transform might be easier if we would expect (somehow?) the aspect ratio to change - it's just updating a matrix uniform instead of a (admittedly very small) vertex buffer.
